"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[log]
enabled = true

[mgr]
ratio          = [ 2, 5, 8 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
sort_translit  = false
linemode       = "none"
show_hidden    = true
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi: {cwd}"

[preview]
wrap            = "yes"
tab_size        = 5
max_width       = 2500
max_height      = 1500
cache_dir       = "/tmp/yaziimgcache"
image_delay     = 30
image_filter    = "triangle"
image_quality   = 75
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
cd = [
	{ run = 'bash ~/.config/yazi/changedir.sh "$1"', desc = "CD", block = true, for = "unix" },
]
edit = [
	{ run = '${EDITOR:-nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$1"', desc = "Open", for = "linux" },
]
setbg = [
	{ run = 'swww img "$1" --transition-fps 144 --transition-type top --transition-duration 1', orphan = true, desc = "setbg", for = "linux" },
]
view = [
	{ run = 'loupe "$1"', orphan = true, desc = "View", for = "linux" },
]
read = [
	{ run = 'zathura "$1"', orphan = true, desc = "Read", for = "linux" },
]
reveal = [
	{ run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" },
]
extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
]
play = [
	{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]

[[open.prepend_rules]]
name = "*/"
use = [ "cd", "edit", "reveal" ]

[tasks]
micro_workers    = 10
macro_workers    = 10
bizarre_retry    = 3
image_alloc      = 536870912
image_bound      = [ 0, 0 ]
suppress_preload = false

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[[plugin.prepend_previewers]]
name = "*.flac"
run  = "piper"

[[plugin.prepend_previewers]]
name = "*.md"
run  = "piper"
